#!/bin/bash

# This Bash script automates the generation of photo descriptions using the Gemini CLI.
# It processes image files in the 'web/photos' directory, generates a descriptive text for each,
# and saves the output to a JSON file. The script includes logic for retrying failed attempts
# and handling rate limits.
#
# Requirements: jq, gemini CLI
# This script was originally generated by AI.

set -e

# --- Configuration ---
OUTPUT_FILE="description.json"
PROMPT_TEMPLATE="Describe this photo of Renzo in 1 sentence. Renzo is a German Shepherd. If a yellow Labrador appears in the photo, that is his brother Elliott. Make it heartwarming and respectful. Keep it generic and light-hearted, do not over-explain. Return ONLY the description text, exactly 1 sentence, no extra formatting or explanations."
MAX_RETRIES=3
RETRY_DELAY=5
RATE_LIMIT_DELAY=60
GEMINI_MODEL="gemini-2.5-flash"
SUCCESS_DELAY=8

# --- Script ---

# Change to the photos directory
cd "web/photos" || exit 1

# Check if jq is installed
if ! command -v jq &> /dev/null; then
    echo "Error: jq is required but not installed. Install it with: sudo pacman -S jq" >&2
    exit 1
fi

# Check if gemini CLI is installed
if ! command -v gemini &> /dev/null; then
    echo "Error: gemini CLI is required but not installed." >&2
    exit 1
fi

# Load existing descriptions
declare -A descriptions
if [ -f "$OUTPUT_FILE" ]; then
    echo "Loading existing descriptions from $OUTPUT_FILE"
    while IFS="=" read -r key value; do
        descriptions["$key"]="$value"
    done < <(jq -r 'to_entries | .[] | "\(.key)=\(.value)"' "$OUTPUT_FILE" 2>/dev/null || true)
fi

# Get all image files
mapfile -t all_photos < <(find . -maxdepth 1 -type f \( -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.png" -o -iname "*.gif" \) ! -name "$OUTPUT_FILE" -printf "%f\n" | sort)

# Filter out photos that already have descriptions
photos=()
for photo in "${all_photos[@]}"; do
    if [ -z "${descriptions[$photo]}" ]; then
        photos+=("$photo")
    fi
done

echo "Found ${#all_photos[@]} total photos, ${#photos[@]} missing descriptions..."
if [ ${#photos[@]} -eq 0 ]; then
    echo "All photos already have descriptions! Exiting..."
    exit 0
fi

# Function to save descriptions to JSON
save_descriptions() {
    local temp_file=$(mktemp)
    echo "{" > "$temp_file"
    local first=true
    for key in $(printf '%s\n' "${!descriptions[@]}" | sort); do
        if [ "$first" = true ]; then
            first=false
        else
            echo "," >> "$temp_file"
        fi
        printf '  "%s": %s' "$key" "$(printf '%s' "${descriptions[$key]}" | jq -R -s .)" >> "$temp_file"
    done
    echo "" >> "$temp_file"
    echo "}" >> "$temp_file"

    if mv "$temp_file" "$OUTPUT_FILE"; then
        return 0
    else
        rm -f "$temp_file"
        return 1
    fi
}

# Function to process a single photo
process_photo() {
    local photo="$1"
    echo "Processing $photo..."

    # Call Gemini CLI and capture output
    local prompt="$PROMPT_TEMPLATE @$photo"
    local description=$(timeout 180 gemini --skip-trust --model "$GEMINI_MODEL" -p "$prompt" 2>/dev/null | grep -v -E '^(Ripgrep|Gemini CLI|Loaded cached|Data collection)' | tr -d '\r' | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//' | sed '/^$/d' | tail -n 1)

    # Check if description is valid
    if [ -n "$description" ] && ! echo "$description" | grep -qi "error\|failed\|could not\|unable to"; then
        descriptions["$photo"]="$description"
        echo "✓ Added description for $photo"

        # Save JSON after each successful description
        if save_descriptions; then
            echo "  → Saved to $OUTPUT_FILE (${#descriptions[@]} total)"
        fi
        return 0
    else
        return 1
    fi
}

# Arrays to track failures
declare -a failed_photos

# Process all photos with retry logic
for photo in "${photos[@]}"; do
    retry_count=0
    success=false

    while [ $retry_count -lt $MAX_RETRIES ] && [ "$success" = false ]; do
        if [ $retry_count -gt 0 ]; then
            echo "Retrying $photo (attempt $((retry_count + 1))/$MAX_RETRIES)..."
            sleep $RETRY_DELAY
        fi

        if process_photo "$photo"; then
            success=true
            sleep $SUCCESS_DELAY
        else
            echo "✗ No description received for $photo (attempt $((retry_count + 1)))"
            retry_count=$((retry_count + 1))

            # Check for possible rate limit
            if [ $retry_count -eq 2 ]; then
                echo "⏱️  Possible rate limit hit. Waiting $RATE_LIMIT_DELAY seconds..."
                sleep $RATE_LIMIT_DELAY
            fi
        fi
    done

    # If all retries failed, add to failed list
    if [ "$success" = false ]; then
        failed_photos+=("$photo")
        echo "⚠️  $photo failed after $MAX_RETRIES attempts, adding to retry queue"
    fi
done

# Process failed photos one more time after a longer delay
if [ ${#failed_photos[@]} -gt 0 ]; then
    echo ""
    echo "🔄 Processing ${#failed_photos[@]} failed photos after extended delay..."
    sleep $((RATE_LIMIT_DELAY * 2))

    still_failed=()

    for photo in "${failed_photos[@]}"; do
        echo "Final attempt for $photo..."
        if process_photo "$photo"; then
            sleep $SUCCESS_DELAY
        else
            still_failed+=("$photo")
        fi
    done

    if [ ${#still_failed[@]} -gt 0 ]; then
        echo ""
        echo "❌ Still failed photos:"
        printf '  - %s\n' "${still_failed[@]}"

        # Save failed photos to a text file
        printf '%s\n' "${still_failed[@]}" > failed_photos.txt
        echo ""
        echo "💾 Failed photos saved to failed_photos.txt for manual retry"
    fi
fi

echo ""
echo "✅ Processing complete!"
echo "Successfully processed: ${#descriptions[@]} photos"
echo "Failed photos: ${#still_failed[@]}"
echo "Results saved to: $OUTPUT_FILE"
